### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tsubi-kaiju** [tsubi-kaiju/furima-39378#23]
# URL
- フリマアプリのURL
  - https://furima-39378.onrender.com/
- Basic認証
  - ID：admin
  - パスワード：14939378
- 出品者
  - メールアドレス：hoge@sample.com
  - パスワード：hogehoge1
- 購入者
  - メールアドレス：piyo@sample.com
  - パスワード：piyopiyo1

**Comment by shodai-ito** [comment]
@tsubi-kaiju さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`出品機能`**
- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
手数料と利益の合計が価格と一致しません。
<img width="658" alt="スクリーンショット 2023-11-03 9 38 41" src="https://github.com/tsubi-kaiju/furima-39378/assets/62537107/0dc7383a-fa83-4c56-b1fb-b01ba233cf23">

- [x] **エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
「空白である」ことと、「１文字未満である」ことは同義かと存じます。
メッセージは異なりますが、意味合いが重複しているため一つにまとめましょう。
<img width="555" alt="スクリーンショット 2023-11-03 9 39 53" src="https://github.com/tsubi-kaiju/furima-39378/assets/62537107/56c22090-d1ef-4fa5-aea3-4502aee589e2">

### **`詳細機能`**
- [x] **商品詳細表示ページは、ログイン状況や商品の販売状況に関係なく、誰でも見ることができること**
ログアウト状態で詳細ページに遷移しようとするとエラーになります。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tsubi-kaiju** [comment]
レビューいただきありがとうございます！
修正し本番環境での動作確認も完了しました。
再度ご確認をお願いいたします。

**Comment by moom1122** [comment]
@tsubi-kaiju さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by tsubi-kaiju** [comment]
@moom1122  @shodai-ito
LGTMありがとうございます！
親切にサポートしてくださったテックキャンプの皆様ありがとうございました！
